### ISSUE TITLE
Just installed and spotted something odd

### ISSUE THREAD

**Issue by emrul** [michaelnny/deep_rl_zoo#10]
https://github.com/michaelnny/deep_rl_zoo/blob/17c4efe5bc7391fe65a2ea785f74c8c539782f74/deep_rl_zoo/gym_env.py#L228

I'm not sure if the `else` should be here? It seems like then `obs` would end up undefined on the next line where you do `obs.copy()`?

**Comment by michaelnny** [comment]
As mentioned at the header, the code related to Atari environment preprocessing is copied from OpenAI's baseline, we've only made small changes (like Doc Strings, change function/class names). You might get better answer from there.

https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py

**Comment by KiwiXR** [comment]
IMO, there might be a real mistake in the adapted code.

In baseline's code, the argument is named as `obs`:

https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L166

and then this `obs` is used in the `else` branch:

https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L183

In this repo, however, the argument is renamed into `observation`:

https://github.com/michaelnny/deep_rl_zoo/blob/ab3035134daa4e6f2d57758bd8a3a7e48bea5b53/deep_rl_zoo/gym_env.py#L211

but the reference to it is not updated accordingly, which might be the source of confusion:

https://github.com/michaelnny/deep_rl_zoo/blob/ab3035134daa4e6f2d57758bd8a3a7e48bea5b53/deep_rl_zoo/gym_env.py#L229

and a simple fix might be `obs = observation.copy()`.

There might be something I failed to notice, so please correct me if I am wrong.

**Comment by michaelnny** [comment]
Hi,

If you look closely in the original implementation from the below link, you'll see that they never set the `dict_space_key` when using the WarpFrame wrapper. The same is true in our code.

https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L275-L290

So this means the block which is causing your concern was never executed. I guess this is the kind of downside of copying and adapting other people's code where we don't have proper documentation to describe what they're doing. We might need to remove all these blocks to avoid further confusion.
