### ISSUE TITLE
Meme paper

### ISSUE THREAD

**Issue by hlsafin** [michaelnny/deep_rl_zoo#11]
I love your work, are we going to see an implementation of MEME ( https://arxiv.org/abs/2209.07550 ) by paper anytime in the future? I think it's a big improvement upon Agent57. 

Thank you

**Comment by michaelnny** [comment]
Thank you for your interests in the project. Right now I'm planning and working on some personal stuff, so I can't say if there's going to be any new implementation or feature improvement in the near future (3-4 months).

**Comment by hlsafin** [comment]
Thank you
