### ISSUE TITLE
Bug in curiosity.py

### ISSUE THREAD

**Issue by YHL04** [michaelnny/deep_rl_zoo#13]
https://github.com/michaelnny/deep_rl_zoo/blob/main/deep_rl_zoo/curiosity.py

distance_rate = torch.min((distance_rate - self._cluster_distance), torch.tensor(0.0))

I think this should be torch.max instead of torch.min

**Comment by michaelnny** [comment]
Hi, thanks for reporting the bug, we'll try to fix it as soon as possible.

**Comment by michaelnny** [comment]
Fixed with commit [e06fd3f](https://github.com/michaelnny/deep_rl_zoo/commit/e06fd3f5e2b336197e71f91562757d9169701697)
