### ISSUE TITLE
MEME paper

### ISSUE THREAD

**Issue by YHL04** [michaelnny/deep_rl_zoo#14]
I'm currently reimplementing Agent57 to understand the concepts thoroughly, im almost done except batch inference and multi actor, retrace, meta controller, bandits, and multi head q value. Would you be interested in working on an open source MEME agent together for the ultimate reinforcement learning agent outside of this repository? I'm also considering swapping GTrXL for the main model.

**Comment by michaelnny** [comment]
Thanks for reaching out. Unfortunately we don't have the time and resource to implement that in the near feature as we've been busy trying to catch on how RL can be used in training LLM.
