### ISSUE TITLE
agent57 priorities

### ISSUE THREAD

**Issue by hlsafin** [michaelnny/deep_rl_zoo#16]
I am not sure how you got this from Agent57, (agent.py). I don't see this mentioned in the original paper.
line 676 "priorities = 0.8 * ext_priorities + 0.2 * int_priorities"
Thanks

**Comment by michaelnny** [comment]
You're correct this does not mentioned in the paper. This is just one of the many gray areas where we have to try different things and hope it will work, as most of the papers don't include the fine details.

**Comment by hlsafin** [comment]
thank you
