### ISSUE TITLE
Numerical issues when advantage_t.std() is 0 in PPO

### ISSUE THREAD

**Issue by jagandecapri** [michaelnny/deep_rl_zoo#17]
Hi @michaelnny ,

When I ran experiments, I found there were cases of division by 0 when the `advantage_t.std()` is `0` at [here](https://github.com/michaelnny/deep_rl_zoo/blob/e06fd3f5e2b336197e71f91562757d9169701697/deep_rl_zoo/ppo/agent.py#L398) which then yields `-inf` or `inf` as the `advantage_t`. Would it make sense to add a small epsilon value, i.e: `1e-10`, to avoid the division by `0`.

On a side note, thank you for this amazing repository. 💯

**Comment by michaelnny** [comment]
Hi,

You're correct that was indeed a bug, it's a common practice to add a small value like 1e-8 to the denominator to avoid division by zero. Thanks for point that out, I'll try to fix that in the weekend.

Also, very glad to hear that you found the work helpful.

**Comment by jagandecapri** [comment]
Thank you, @michaelnny!

**Comment by michaelnny** [comment]
fixed in 1b5450e
