### ISSUE TITLE
multigpu agent57

### ISSUE THREAD

**Issue by hlsafin** [michaelnny/deep_rl_zoo#6]
I'm having issues running multigpu on Agent57 in the same way I run them on let's say R2D2.
Where I change 
`    actor_devices = [runtime_device] * FLAGS.num_actors`
to
`    actor_devices = [torch.device('cuda:0'),torch.device('cuda:1')....etc etc] * FLAGS.num_actors`
So this works for R2D2 but not Agent57, howcome? 
Thank you.

**Comment by michaelnny** [comment]
Hi,

There are more stuff involved in Agent57, as it uses RND networks and meta controllers. Unfortunately we don't have access to multiple GPUs on our side, so it's hard to debug this. And we don't plan to support this feature at the moment.

Thank you for reporting the issue.
