### ISSUE TITLE
AttributeError: 'str' object has no attribute 'reset'

### ISSUE THREAD

**Issue by sdmeers** [michaelnny/deep_rl_zoo#8]
Hi,

I'm trying to get this running but am getting an attribute error when trying to evaluate a DQN agent against Lunar Lander v2 as a test. The training seems to have completed correctly and a ckpt file created (although it seems small, only 38 kB). The traceback I'm getting is below. I'm running on Ubuntu 22.04 within a virtual environment. I have had the same error using both venv and conda.

python3 -m deep_rl_zoo.dqn.eval_agent --environment_name=LunarLander-v2 --load_checkpoint_file=saved_checkpoints/DQN_LunarLander-v2_1.ckpt
I1117 23:38:12.875501 139881514845120 eval_agent.py:91] Environment: LunarLander-v2
I1117 23:38:12.875638 139881514845120 eval_agent.py:92] Action spec: 4
I1117 23:38:12.875766 139881514845120 eval_agent.py:93] Observation spec: 8
I1117 23:38:14.595612 139881514845120 main_loop.py:662] Testing iteration 0
Traceback (most recent call last):
  File "/home/sdmeers/miniconda3/envs/deep_rl_zoo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sdmeers/miniconda3/envs/deep_rl_zoo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sdmeers/OneDrive/Steve/Code/deep_rl_zoo/deep_rl_zoo/dqn/eval_agent.py", line 125, in <module>
    app.run(main)
  File "/home/sdmeers/miniconda3/envs/deep_rl_zoo/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/sdmeers/miniconda3/envs/deep_rl_zoo/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/sdmeers/OneDrive/Steve/Code/deep_rl_zoo/deep_rl_zoo/dqn/eval_agent.py", line 114, in main
    main_loop.run_evaluation_iterations(
  File "/home/sdmeers/OneDrive/Steve/Code/deep_rl_zoo/deep_rl_zoo/main_loop.py", line 666, in run_evaluation_iterations
    eval_stats = run_env_steps(num_eval_frames, eval_agent, eval_env, eval_tb_log_dir)
  File "/home/sdmeers/OneDrive/Steve/Code/deep_rl_zoo/deep_rl_zoo/main_loop.py", line 133, in run_env_steps
    stats = trackers_lib.generate_statistics(trackers, seq_truncated)
  File "/home/sdmeers/OneDrive/Steve/Code/deep_rl_zoo/deep_rl_zoo/trackers.py", line 375, in generate_statistics
    tracker.reset()
AttributeError: 'str' object has no attribute 'reset' 

pip freeze is as follows 

absl-py==1.3.0
ale-py==0.7.5
AutoROM==0.4.2
AutoROM.accept-rom-license==0.4.2
black==22.10.0
box2d-py==2.3.8
cachetools==5.2.0
certifi @ file:///croot/certifi_1665076670883/work/certifi
cfgv==3.3.1
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.0
distlib==0.3.6
filelock==3.8.0
glfw==2.5.5
google-auth==2.14.1
google-auth-oauthlib==0.4.6
grpcio==1.50.0
gym==0.25.2
gym-notices==0.0.8
identify==2.5.8
idna==3.4
imageio==2.22.2
importlib-metadata==5.0.0
importlib-resources==5.10.0
Markdown==3.4.1
MarkupSafe==2.1.1
mujoco==2.2.2
mypy-extensions==0.4.3
nodeenv==1.7.0
numpy==1.23.4
oauthlib==3.2.2
opencv-python==4.6.0.66
pathspec==0.10.2
Pillow==9.3.0
platformdirs==2.5.4
pre-commit==2.20.0
protobuf==3.20.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pygame==2.1.2
pyglet==1.5.27
PyOpenGL==3.1.6
python-snappy==0.6.1
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
six==1.16.0
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
toml==0.10.2
tomli==2.0.1
torch==1.12.1
torchsummary==1.5.1
torchvision==0.13.1
tqdm==4.64.1
typing_extensions==4.4.0
urllib3==1.26.12
virtualenv==20.16.7
Werkzeug==2.2.2
zipp==3.10.0

**Comment by michaelnny** [comment]
Hi,

It seems there's a bug in function `run_evaluation_iterations` in the `main_loop.py` module. We recently refactored the trackers to keep tracking a complete episode statistics (instead of done-on-loss-life) for the Atari games, and unfortunately, we forgot to make the necessary changes to this function, and our testing scripts didn't flag this bug.

Notice this bug will not affect the training scripts like `run_atari` or `run_classic`, and we'll looking at the issue this weekend when we have access to our workstation. Thank you for reporting the issue.

**Comment by michaelnny** [comment]
Should be fixed with commit e6585c31391e8c75465385cc894215a61e6a1f7c

**Comment by sdmeers** [comment]
Fantastic - that's fixed it. Thanks for doing it so quickly.
